server:
  port: 9095

spring:
  application:
    name: CONFIG-SERVER


  cloud:
    config:
      server:
        bootstrap: true
cloud:
   config:
     server:
       git:
         uri: C:\Users\bauhaus\Desktop\miniProject\New folder\Configuration\git.






